CC=gcc
CFLAGS= -g -std=c11 -Wpedantic -Wall

caltool: caltool.o calutil.o date.o

calutil.o: calutil.c calutil.h

caltool.o: caltool.h caltool.h

date.o: date.c

clean:
	rm -f *.o caltool


















